import React from 'react';
import { BadgeCheck, PhoneCall } from 'lucide-react';
import Link from '../components/Link';
import ServiceCard from '../components/ServiceCard';
import services from '../data/services';

export default function ServicesPage() {
  return <main className="pb-20 pt-12"><section className="mx-auto max-w-7xl space-y-6 px-4 text-center sm:px-6 lg:px-8"><span className="inline-flex rounded-full border border-accent bg-accent/30 px-3 py-1 text-xs font-semibold uppercase tracking-[.16em] text-primary">Professional Tree Care & Field Operations</span><h1 className="mx-auto max-w-4xl font-heading text-4xl font-extrabold leading-tight tracking-tight sm:text-5xl lg:text-6xl">Comprehensive Tree Care & <span className="text-primary underline decoration-accent/60 underline-offset-4">Arborist Services</span></h1><p className="mx-auto max-w-2xl text-lg leading-relaxed text-muted-foreground sm:text-xl">From 24/7 emergency storm response and hazardous tree removal to precision pruning and stump grinding, our licensed arborist crews protect your property value and safety.</p><div className="flex flex-col items-center justify-center gap-4 pt-4 sm:flex-row"><Link to="/contact" className="flex h-11 items-center justify-center gap-2 rounded-md bg-primary px-8 text-sm font-semibold text-primary-foreground shadow-md"><PhoneCall className="h-4 w-4" /> Request Free Tree Inspection</Link><a href="#services" className="flex h-11 items-center justify-center rounded-md border border-border bg-background px-8 text-sm font-medium hover:bg-secondary">Explore All Services</a></div></section><section id="services" className="mx-auto max-w-7xl px-4 pt-20 sm:px-6 lg:px-8"><div className="mx-auto mb-12 max-w-2xl space-y-3 text-center"><h2 className="font-heading text-3xl font-bold">Our Core Tree Services</h2><p className="text-sm text-muted-foreground">Fully licensed, insured, and equipped with state-of-the-art forestry equipment and ISA-certified arborist expertise.</p></div><div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => <ServiceCard key={service.title} service={service} />)}</div></section><section className="mx-auto mt-20 max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-2xl bg-primary px-6 py-12 text-center text-primary-foreground sm:px-12"><BadgeCheck className="mx-auto mb-4 h-9 w-9 text-accent" /><h2 className="font-heading text-3xl font-bold">Need a Certified Tree Care Crew?</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-primary-foreground/80">Tell us about your property and receive a clear written recommendation from our arborist team.</p><a href="tel:+17165892600" className="mt-7 inline-flex h-11 items-center gap-2 rounded-md bg-background px-7 text-sm font-semibold text-foreground"><PhoneCall className="h-4 w-4" /> Request Your Free Inspection</a></div></section></main>;
}
